#!/usr/bin/env node
/* Stage the built page into the iOS project, and stamp the version.
 *
 * The twin of tools/build-android.mjs, and deliberately so: both platforms get
 * the same dist/app.html — no photographs, none of the website-only sections —
 * so the two apps cannot quietly diverge into different products. Anything
 * that is true of one here is true of the other.
 *
 *   node tools/build-ios.mjs
 *
 * What it does not do is build. That needs Xcode, which needs macOS, and this
 * runs wherever you are. .github/workflows/ios.yml does the rest on a macOS
 * runner — which is also the honest answer to "do I need a Mac to ship this":
 * no, but something does, and GitHub rents one by the minute.
 */

import { cpSync, mkdirSync, rmSync, existsSync, readFileSync, writeFileSync, statSync, readdirSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const www = join(root, 'ios/Overland/Resources/www')

/* Built here rather than expected to be lying around, so there is no way to
 * ship an app made from whatever the last build happened to leave behind. */
execFileSync(process.execPath, [join(root, 'tools/build.mjs')], {
  cwd: root,
  env: { ...process.env, APP: '1' },
  stdio: 'inherit',
})

rmSync(www, { recursive: true, force: true })
mkdirSync(www, { recursive: true })

cpSync(join(root, 'dist/app.html'), join(www, 'index.html'))
cpSync(join(root, 'dist/app.js'), join(www, 'app.js'))

/* Both, or neither is worth shipping.
 *
 * The page loads the program as a subresource, and a missing subresource never
 * reaches the navigation delegate — that only fires for the main frame. So an
 * app staged without app.js reports nothing: it opens, draws the empty shell,
 * and sits there. Caught here, where it can still be a build failure instead of
 * a one-star review. */
for (const [name, min] of [['index.html', 50_000], ['app.js', 500_000]]) {
  const at = join(www, name)
  if (!existsSync(at) || statSync(at).size < min) {
    console.error(`ios                ${name} missing or truncated in www — refusing to stage`)
    process.exit(1)
  }
}

/* CFBundleVersion has to rise on every upload and App Store Connect rejects a
 * repeat, exactly as Play does — so it is derived from the same clock, in the
 * same ten-minute steps, from the same epoch. Two schemes for two stores would
 * be one more thing to reason about on the day a build is rejected.
 *
 * Ten minutes rather than days: a bug found in a build that has already been
 * uploaded gets fixed the same day, which under a daily counter is the same
 * number and a rejection. Which is what happened on the Android side. */
const EPOCH = Date.UTC(2026, 0, 1)
const ticks = Math.floor((Date.now() - EPOCH) / 600000)
const version =
  readFileSync(join(root, 'package.json'), 'utf8').match(/"version":\s*"([^"]+)"/)?.[1] || '1.0.0'

/* An xcconfig rather than an edited Info.plist: the plist references these by
 * name, so the generated project picks them up without anything rewriting XML
 * in place — and a failed build leaves no half-stamped file behind. */
writeFileSync(
  join(root, 'ios/Version.xcconfig'),
  `// Generated by tools/build-ios.mjs — do not edit by hand.\n` +
    `MARKETING_VERSION = ${version}\n` +
    `CURRENT_PROJECT_VERSION = ${ticks}\n`
)

const bytes = (function size(dir) {
  let n = 0
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name)
    n += e.isDirectory() ? size(p) : statSync(p).size
  }
  return n
})(www)

console.log(
  `ios                www ${(bytes / 1024 / 1024).toFixed(1)} MB, version ${version} (${ticks})`
)
