#!/usr/bin/env node
/* Stage the built page into the Android project's assets.
 *
 * The app is a WebView over the same HTML the website serves — not because
 * wrapping a site is a good way to make an app, but because this particular
 * page already is one. It fetches nothing at runtime, so bundling it produces
 * something that genuinely works with the phone in flight mode at a border
 * post, which is exactly where you need it and exactly where a website is
 * useless.
 *
 * It builds its own page rather than staging the website's. dist/app.html
 * carries no photographs at all: the library is 22 MB of a 46 MB app, and the
 * drawn scene art it falls back to is the same art the page already uses for
 * every station without a photograph. It also leaves out the parts that only
 * make sense on a website — the links to the written-up route pages, which are
 * separate documents on the site and would be dead ends inside one file.
 *
 *   node tools/build-android.mjs
 */

import { cpSync, mkdirSync, rmSync, existsSync, readFileSync, writeFileSync, statSync, readdirSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const assets = join(root, 'android/app/src/main/assets')

/* Built here rather than expected to be lying around, so there is no way to
 * ship an app made from whatever the last build happened to leave behind. */
execFileSync(process.execPath, [join(root, 'tools/build.mjs')], {
  cwd: root,
  env: { ...process.env, APP: '1' },
  stdio: 'inherit',
})

rmSync(assets, { recursive: true, force: true })
mkdirSync(assets, { recursive: true })

cpSync(join(root, 'dist/app.html'), join(assets, 'index.html'))

/* The version code has to rise on every upload and Play rejects a repeat, so
 * it is derived rather than remembered: time since the project's epoch, which
 * increments on its own and can never go backwards.
 *
 * Ten-minute steps, not days. Days reads better and is wrong the first time a
 * bug is found in a build that has already been uploaded — the fix is the same
 * day, so it carries the same code, and Play rejects it. Which is exactly what
 * happened. Ten minutes is finer than anyone can rebuild and still leaves the
 * counter four thousand years short of the 2100000000 ceiling.
 *
 * A version code can never be lowered once Play has seen it, so this is a
 * one-way step from the old scheme: 209 became 30016 and there is no route
 * back. That is the cost of the change and it is paid once. */
const EPOCH = Date.UTC(2026, 0, 1)
const ticks = Math.floor((Date.now() - EPOCH) / 600000)
const versionName = readFileSync(join(root, 'package.json'), 'utf8').match(/"version":\s*"([^"]+)"/)?.[1] || '1.0.0'
writeFileSync(
  join(root, 'android/version.properties'),
  `# Generated by tools/build-android.mjs — do not edit by hand.\n` +
    `versionCode=${ticks}\nversionName=${versionName}\n`
)

const bytes = (function size(dir) {
  let n = 0
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name)
    n += e.isDirectory() ? size(p) : statSync(p).size
  }
  return n
})(assets)

console.log(
  `android            assets ${(bytes / 1024 / 1024).toFixed(1)} MB, ` +
    `version ${versionName} (${ticks})`
)
