#!/usr/bin/env python3
"""Subset the three typefaces down to the glyphs this app actually renders and
emit them as a single CSS file of @font-face data URIs.

The Artifact CSP blocks font CDNs, so the faces have to travel inside the page.
Subsetting keeps that affordable: ~1.1 MB of source TTF becomes ~60 KB of woff2.

Station names carry Vietnamese diacritics (Huế, Đà Nẵng, Hải Phòng), so Latin
Extended Additional is not optional — drop it and words break mid-glyph into a
fallback face.

    pip install fonttools brotli
    python3 tools/build-fonts.py <ttf-dir> src/fonts.css
"""

import base64
import sys
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

UNICODES = [
    (0x0020, 0x007E),  # basic latin
    (0x00A0, 0x00FF),  # latin-1 supplement
    (0x0100, 0x017F),  # latin extended-A
    (0x0180, 0x024F),  # latin extended-B — Ơơ Ưư for Vietnamese
    (0x0300, 0x036F),  # combining marks
    (0x0E3F, 0x0E3F),  # ฿ baht
    (0x1E00, 0x1EFF),  # latin extended additional — Vietnamese precomposed
    (0x2010, 0x2027),  # dashes, quotes, ellipsis
    (0x2030, 0x205E),  # per-mille, primes, bullet
    (0x20A0, 0x20BF),  # currency (₫ ₭ ₱)
    (0x2190, 0x21FF),  # arrows (→ ↔)
    (0x2202, 0x22FF),  # maths (≈ ≥ ≤)
    (0x25A0, 0x25FF),  # geometric shapes for legend marks
]

FACES = [
    # file,                          family,        weight, style
    ("BarlowCondensed-Medium.ttf",   "BarlowCond",  500, "normal"),
    ("BarlowCondensed-SemiBold.ttf", "BarlowCond",  600, "normal"),
    ("Spectral-Regular.ttf",         "Spectral",    400, "normal"),
    ("IBMPlexMono-Regular.ttf",      "PlexMono",    400, "normal"),
    ("IBMPlexMono-SemiBold.ttf",     "PlexMono",    600, "normal"),
]


def unicode_arg() -> str:
    parts = []
    for lo, hi in UNICODES:
        parts.append(f"U+{lo:04X}" if lo == hi else f"U+{lo:04X}-{hi:04X}")
    return ",".join(parts)


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: build-fonts.py <ttf-dir> <out.css>", file=sys.stderr)
        return 1

    src_dir = Path(sys.argv[1])
    out_path = Path(sys.argv[2])

    blocks = [
        "/* Generated by tools/build-fonts.py — do not edit by hand.",
        " * Barlow Condensed, Spectral and IBM Plex Mono, all SIL Open Font License 1.1,",
        " * subset to the glyph set this app renders. */",
        "",
    ]
    total = 0

    for filename, family, weight, style in FACES:
        src = src_dir / filename
        if not src.exists():
            print(f"missing: {src}", file=sys.stderr)
            return 1

        font = TTFont(str(src))
        options = subset.Options()
        options.flavor = "woff2"
        options.layout_features = ["kern", "liga", "calt", "ccmp", "mark", "mkmk"]
        options.desubroutinize = True
        options.hinting = False
        options.notdef_outline = False
        options.name_IDs = ["*"]
        options.drop_tables += ["DSIG"]

        subsetter = subset.Subsetter(options=options)
        subsetter.populate(unicodes=subset.parse_unicodes(unicode_arg()))
        subsetter.subset(font)

        tmp = src.with_suffix(".subset.woff2")
        font.flavor = "woff2"
        font.save(str(tmp))
        payload = tmp.read_bytes()
        total += len(payload)
        print(f"  {filename:32s} {len(payload) / 1024:6.1f} KB")

        b64 = base64.b64encode(payload).decode("ascii")
        blocks.append(
            "@font-face{"
            f"font-family:'{family}';"
            f"font-style:{style};"
            f"font-weight:{weight};"
            "font-display:block;"
            f"src:url(data:font/woff2;base64,{b64}) format('woff2')"
            "}"
        )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(blocks) + "\n", encoding="utf-8")
    print(f"  {'total woff2':32s} {total / 1024:6.1f} KB -> {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
