#!/usr/bin/env node
/* Stage the built page into the Android project's assets.
 *
 * The app is a WebView over the same HTML the website serves — not because
 * wrapping a site is a good way to make an app, but because this particular
 * page already is one. It fetches nothing at runtime, so bundling it produces
 * something that genuinely works with the phone in flight mode at a border
 * post, which is exactly where you need it and exactly where a website is
 * useless.
 *
 * index.html rather than dist/planner.html: the fragment inlines only the
 * photographs that fit a 3 MB budget, and an app has no such budget. Copying
 * the linked set alongside gets all 93 offline too.
 *
 *   node tools/build.mjs && node tools/build-android.mjs
 */

import { cpSync, mkdirSync, rmSync, existsSync, readFileSync, writeFileSync, statSync, readdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const assets = join(root, 'android/app/src/main/assets')

if (!existsSync(join(root, 'index.html'))) {
  console.error('android            index.html missing — run tools/build.mjs first')
  process.exit(1)
}

rmSync(assets, { recursive: true, force: true })
mkdirSync(join(assets, 'data'), { recursive: true })

cpSync(join(root, 'index.html'), join(assets, 'index.html'))
if (existsSync(join(root, 'data/photos'))) {
  cpSync(join(root, 'data/photos'), join(assets, 'data/photos'), { recursive: true })
}

/* The version code has to rise on every upload and Play rejects a repeat, so
 * it is derived rather than remembered: days since the project's epoch, which
 * increments on its own and can never go backwards. */
const EPOCH = Date.UTC(2026, 0, 1)
const days = Math.floor((Date.now() - EPOCH) / 86400000)
const versionName = readFileSync(join(root, 'package.json'), 'utf8').match(/"version":\s*"([^"]+)"/)?.[1] || '1.0.0'
writeFileSync(
  join(root, 'android/version.properties'),
  `# Generated by tools/build-android.mjs — do not edit by hand.\n` +
    `versionCode=${days}\nversionName=${versionName}\n`
)

const bytes = (function size(dir) {
  let n = 0
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name)
    n += e.isDirectory() ? size(p) : statSync(p).size
  }
  return n
})(assets)

console.log(
  `android            assets ${(bytes / 1024 / 1024).toFixed(1)} MB, ` +
    `version ${versionName} (${days})`
)
